-- Vx__create_postagem.sql  (ajuste o x para a próxima versão)
-- Cria a tabela 'postagem' e FK para 'usuario(id)'

CREATE TABLE IF NOT EXISTS postagem (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(200) NOT NULL,
    conteudo    TEXT NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_id  INTEGER NOT NULL,
    CONSTRAINT fk_postagem_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- Índice para acelerar buscas por usuario
CREATE INDEX IF NOT EXISTS idx_postagem_usuario_id ON postagem (usuario_id);
